Website = "https://github.com/oneclickvirt/ecs-gui"

[Details]
Icon = "assets/icons/logo.png"
Name = "goecs"
ID = "com.oneclickvirt.goecs"
Version = "0.1.159"
Build = 1

[Android]
MinVersion = 24
TargetVersion = 34
Arch = ["arm64", "x86_64"]
